import {
  IndikatorOrganisasi,
  IndikatorTahunan,
  IndikatorTriwulan,
  RencanaKerjaBulanan,
  RencanaKerjaHarian,
  Triwulan,
  Bulan,
  StatusPekerjaan,
  SatuanPengukuran,
} from "@/types/kinerja";

// Data Indikator Organisasi
export const mockIndikatorOrganisasi: IndikatorOrganisasi[] = [
  {
    id: "iko-001",
    kodeIndikator: "IKO-2024-001",
    namaIndikator: "Peningkatan Kualitas Pelayanan Publik",
    deskripsi: "Meningkatkan kepuasan masyarakat terhadap pelayanan publik",
    tahunAnggaran: 2024,
    targetOrganisasi: 100,
    satuanPengukuran: SatuanPengukuran.PERSENTASE,
    unitPenanggungJawab: "Dinas Komunikasi dan Informatika",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
];

// Data Indikator Tahunan
export const mockIndikatorTahunan: IndikatorTahunan[] = [
  {
    id: "ikt-001",
    indikatorOrganisasiId: "iko-001",
    nipASN: "199001012015031001",
    namaASN: "Budi Santoso, S.Kom",
    jabatan: "Kepala Seksi Aplikasi",
    unitKerja: "Dinas Komunikasi dan Informatika",
    tahunAnggaran: 2024,
    targetTahunan: 48,
    realisasiTahunan: 32,
    satuanPengukuran: SatuanPengukuran.KEGIATAN,
    keterangan: "Pengembangan aplikasi dan sistem informasi",
    createdAt: new Date("2024-01-05"),
    updatedAt: new Date("2024-08-20"),
  },
  {
    id: "ikt-002",
    indikatorOrganisasiId: "iko-001",
    nipASN: "199105152016032002",
    namaASN: "Siti Aminah, S.T.",
    jabatan: "Analis Teknologi Informasi",
    unitKerja: "Dinas Komunikasi dan Informatika",
    tahunAnggaran: 2024,
    targetTahunan: 40,
    realisasiTahunan: 28,
    satuanPengukuran: SatuanPengukuran.LAPORAN,
    keterangan: "Analisis dan monitoring sistem informasi",
    createdAt: new Date("2024-01-05"),
    updatedAt: new Date("2024-08-20"),
  },
];

// Data Indikator Triwulan
export const mockIndikatorTriwulan: IndikatorTriwulan[] = [
  {
    id: "iktr-001",
    indikatorTahunanId: "ikt-001",
    triwulan: Triwulan.I,
    tahunAnggaran: 2024,
    targetTriwulan: 12,
    realisasiTriwulan: 12,
    satuanPengukuran: SatuanPengukuran.KEGIATAN,
    persentaseCapaian: 100,
    keterangan: "Target triwulan I tercapai 100%",
    createdAt: new Date("2024-01-05"),
    updatedAt: new Date("2024-03-31"),
  },
  {
    id: "iktr-002",
    indikatorTahunanId: "ikt-001",
    triwulan: Triwulan.II,
    tahunAnggaran: 2024,
    targetTriwulan: 12,
    realisasiTriwulan: 11,
    satuanPengukuran: SatuanPengukuran.KEGIATAN,
    persentaseCapaian: 91.67,
    keterangan: "Target triwulan II hampir tercapai",
    createdAt: new Date("2024-04-01"),
    updatedAt: new Date("2024-06-30"),
  },
  {
    id: "iktr-003",
    indikatorTahunanId: "ikt-001",
    triwulan: Triwulan.III,
    tahunAnggaran: 2024,
    targetTriwulan: 12,
    realisasiTriwulan: 9,
    satuanPengukuran: SatuanPengukuran.KEGIATAN,
    persentaseCapaian: 75,
    keterangan: "Sedang berjalan",
    createdAt: new Date("2024-07-01"),
    updatedAt: new Date("2024-08-20"),
  },
  {
    id: "iktr-004",
    indikatorTahunanId: "ikt-001",
    triwulan: Triwulan.IV,
    tahunAnggaran: 2024,
    targetTriwulan: 12,
    realisasiTriwulan: 0,
    satuanPengukuran: SatuanPengukuran.KEGIATAN,
    persentaseCapaian: 0,
    keterangan: "Belum dimulai",
    createdAt: new Date("2024-10-01"),
    updatedAt: new Date("2024-10-01"),
  },
];

// Data Rencana Kerja Bulanan
export const mockRencanaKerjaBulanan: RencanaKerjaBulanan[] = [
  {
    id: "rkb-001",
    indikatorTriwulanId: "iktr-003",
    bulan: Bulan.JULI,
    tahun: 2024,
    namaKegiatan: "Pengembangan Aplikasi Laporan Kinerja ASN",
    deskripsiKegiatan: "Membuat aplikasi untuk pelaporan kinerja harian ASN",
    targetBulanan: 4,
    realisasiBulanan: 4,
    satuanPengukuran: SatuanPengukuran.KEGIATAN,
    anggaranKegiatan: 15000000,
    statusPelaksanaan: StatusPekerjaan.SELESAI,
    hambatan: "Tidak ada",
    solusi: "-",
    createdAt: new Date("2024-07-01"),
    updatedAt: new Date("2024-07-31"),
  },
  {
    id: "rkb-002",
    indikatorTriwulanId: "iktr-003",
    bulan: Bulan.AGUSTUS,
    tahun: 2024,
    namaKegiatan: "Maintenance Sistem Informasi Kepegawaian",
    deskripsiKegiatan: "Pemeliharaan dan perbaikan bug sistem kepegawaian",
    targetBulanan: 3,
    realisasiBulanan: 3,
    satuanPengukuran: SatuanPengukuran.KEGIATAN,
    anggaranKegiatan: 8000000,
    statusPelaksanaan: StatusPekerjaan.SELESAI,
    hambatan: "Server sempat down 2 hari",
    solusi: "Migrasi ke server cadangan",
    createdAt: new Date("2024-08-01"),
    updatedAt: new Date("2024-08-31"),
  },
  {
    id: "rkb-003",
    indikatorTriwulanId: "iktr-003",
    bulan: Bulan.SEPTEMBER,
    tahun: 2024,
    namaKegiatan: "Integrasi Sistem E-Office dengan SIMPEG",
    deskripsiKegiatan: "Menghubungkan sistem e-office dengan database kepegawaian",
    targetBulanan: 5,
    realisasiBulanan: 2,
    satuanPengukuran: SatuanPengukuran.KEGIATAN,
    anggaranKegiatan: 20000000,
    statusPelaksanaan: StatusPekerjaan.SEDANG_BERJALAN,
    hambatan: "Menunggu API dari vendor SIMPEG",
    solusi: "Koordinasi intensif dengan vendor",
    createdAt: new Date("2024-09-01"),
    updatedAt: new Date("2024-09-20"),
  },
];

// Data Rencana Kerja Harian
export const mockRencanaKerjaHarian: RencanaKerjaHarian[] = [
  {
    id: "rkh-001",
    rencanaKerjaBulananId: "rkb-003",
    tanggal: new Date("2024-09-16"),
    uraianTugas: "Meeting dengan tim vendor SIMPEG untuk finalisasi API documentation",
    kuantitasOutput: 1,
    satuanOutput: SatuanPengukuran.KEGIATAN,
    waktuMulai: "09:00",
    waktuSelesai: "12:00",
    durasiMenit: 180,
    statusPelaksanaan: StatusPekerjaan.SELESAI,
    hasilKerja: "Dokumen API telah diterima dan direview",
    buktiDokumen: "/uploads/api-doc-simpeg.pdf",
    keterangan: "Meeting berjalan lancar",
    createdAt: new Date("2024-09-16"),
    updatedAt: new Date("2024-09-16"),
  },
  {
    id: "rkh-002",
    rencanaKerjaBulananId: "rkb-003",
    tanggal: new Date("2024-09-17"),
    uraianTugas: "Implementasi endpoint integrasi data pegawai",
    kuantitasOutput: 1,
    satuanOutput: SatuanPengukuran.KEGIATAN,
    waktuMulai: "08:00",
    waktuSelesai: "16:00",
    durasiMenit: 480,
    statusPelaksanaan: StatusPekerjaan.SELESAI,
    hasilKerja: "Endpoint /api/pegawai berhasil dibuat dan testing sukses",
    buktiDokumen: "/uploads/testing-result-pegawai.png",
    keterangan: "Testing mencakup 50 data pegawai",
    createdAt: new Date("2024-09-17"),
    updatedAt: new Date("2024-09-17"),
  },
  {
    id: "rkh-003",
    rencanaKerjaBulananId: "rkb-003",
    tanggal: new Date("2024-09-18"),
    uraianTugas: "Testing integrasi data absensi dengan e-office",
    kuantitasOutput: 1,
    satuanOutput: SatuanPengukuran.KEGIATAN,
    waktuMulai: "08:00",
    waktuSelesai: "15:00",
    durasiMenit: 420,
    statusPelaksanaan: StatusPekerjaan.SEDANG_BERJALAN,
    hasilKerja: "Testing masih dalam proses, ditemukan beberapa bug minor",
    buktiDokumen: "/uploads/bug-report-18-sept.pdf",
    keterangan: "Perlu koordinasi lanjutan untuk fixing bug",
    createdAt: new Date("2024-09-18"),
    updatedAt: new Date("2024-09-18"),
  },
  {
    id: "rkh-004",
    rencanaKerjaBulananId: "rkb-003",
    tanggal: new Date("2024-09-19"),
    uraianTugas: "Fixing bug integrasi dan retesting",
    kuantitasOutput: 1,
    satuanOutput: SatuanPengukuran.KEGIATAN,
    waktuMulai: "08:00",
    waktuSelesai: "17:00",
    durasiMenit: 540,
    statusPelaksanaan: StatusPekerjaan.BELUM_DIMULAI,
    hasilKerja: "",
    buktiDokumen: "",
    keterangan: "Dijadwalkan untuk besok",
    createdAt: new Date("2024-09-18"),
    updatedAt: new Date("2024-09-18"),
  },
];
